name: Test Discord Notification

on: 
  workflow_dispatch:

jobs:
  test-discord-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send test notification
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        details: "This is a test notification!"
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
